export const RoadTypes = [
  "Big Road",
  "Bead Road",
  "Eye",
  "Small",
  "Roach",
] as const;
export type RoadTypesType = typeof RoadTypes[number];

export const RawResults = [
  { resultType: 2, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 2, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 2, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
];

export const ResultList = [
  {
    "Id": 1,
    "Winner": "P",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "-",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 2,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 3,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 4,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 5,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 6,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 7,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 8,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 9,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 10,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 11,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 12,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 13,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 14,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 15,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 16,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 17,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 18,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 19,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 20,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 21,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 22,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 23,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 24,
    "Winner": "B",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Win",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": 0.95,
    "Column1": "",
    "Column2": ""
  },
  {
    "Id": 25,
    "Winner": "P",
    "Prediction": "B",
    "DetectedPattern": "-",
    "Result": "Loss",
    "hSkip": false,
    "ugSkip": false,
    "VirtualLossRequired": false,
    "VirtualWinRequired": false,
    "VirtualWoLRequired": false,
    "Bet": -1,
    "Column1": "",
    "Column2": ""
  }
]