export const RoadTypes = [
  "Big Road",
  "Bead Road",
  "Eye",
  "Small",
  "Roach",
] as const;
export type RoadTypesType = typeof RoadTypes[number];

export const RawResults = [
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 2, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 2, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 2, isBankerPair: false, isPlayerPair: false },
  { resultType: 2, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 2, isBankerPair: false, isPlayerPair: false },
  { resultType: 2, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 3, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 2, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 2, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 2, isBankerPair: false, isPlayerPair: false },
  { resultType: 1, isBankerPair: false, isPlayerPair: false },
  { resultType: 2, isBankerPair: false, isPlayerPair: false },
  { resultType: 3, isBankerPair: false, isPlayerPair: false },
  { resultType: 3, isBankerPair: false, isPlayerPair: false },
  { resultType: 3, isBankerPair: false, isPlayerPair: false },
  { resultType: 3, isBankerPair: false, isPlayerPair: false },
];